spring:
  elasticsearch:
    uris: http://localhost:9200
  config:
    import: optional:configserver:http://localhost:5000
  application:
    name: processing-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: transactionGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: transactionNotification:atos.formation.processingservice.dtos.TransactionNotification
  data:
    elasticsearch:
      repositories:
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9097/eureka



fraud:
  api:
    url: http://localhost:5010/predict